

const people = ['Thish', 'Thika']

const truths = [
    '{{choosedPerson}} Share three things you love about {{oppositePerson}}.',
    'When was the last time you lied?',
    'What\'s your biggest fear?',
    'What\'s your biggest fantasy?',
    'Do you have any fetishes?',
    'Have you ever cheated on someone?',
    'What\'s the worst thing you\'ve ever done?',
    'What\'s a secret you\'ve never told anyone?',
    'Have you ever cheated in an exam?',
    'What\'s the most drunk you\'ve ever been?',
    'Have you ever broken the law?',
    "What's the most embarrassing thing you've ever done?",
    "What's your biggest insecurity?",
    "What's the biggest mistake you've ever made?",
    "What's the most disgusting thing you've ever done?",
    "Who would you like to kiss in this room?",
    "What's the worst thing anyone's ever done to you?",
    "Have you ever had a run in with the law?",
    "What's your worst habit?",
    "What's the worst thing you've ever said to anyone?",
    "Have you ever peed in the shower?",
    "What's the strangest dream you've had?",
    "Have you ever been caught doing something you shouldn't have?",
    "What's the worst date you've been on?",
    "What's your biggest regret?",
    "What's the biggest misconception about you?",
    "Where's the weirdest place you've had sex?",
    "Which is your favorite song to hum in the shower?",
    "Have you ever peed while playing on the beach?",
    "Which actor/actress would you swap your life with for 10 days?",
    "Who was your crush in school?",
    "Who was your crush in College?",
    "Did you ever have a crush on a high school teacher?",
    "Beaches or mountains?",
    "{{choosedPerson}}, What is the worst gift you have ever received from {{oppositePerson}}?",
    "{{choosedPerson}}, How many kids are you planning to have?",
    "Tell something you were always afraid to express.",
    "Did you ever start a rumor about someone you hate?",
    "Is there something that you love a lot, but you sacrificed just for me?",
    "Is there a nickname I gave, which you absolutely hate?",
    "Describe your favorite clothing style.",
    "What is that one change you have noticed after marriage?",
    "How perfect am I as your partner?",
    "When was the longest time you have stayed in a bathroom and why?",
    "What was your most embarrassing moment?",
    "Have you ever peed the bed as an adult?",
    "Have you ever had a crush on a teacher?",
    "Have you ever sent a sexy snap to someone?",
    "Have you ever practiced kissing yourself in the mirror?",
    "Have you ever stolen something?",
    "Have you ever been to a sex club? Would you go if you were invited?",
    "Did you ever fantasize about me in your bed? Tell me about it. ",
    "How often do you think couples should have sex to keep the relationship strong?",
    "What was our best kiss like? ",
    "What is the hottest thing someone has ever done with you in bed? ",
    "If you could only have one romantic night every year, what would you do?",
    
    
]

const dares = [
    "{{choosedPerson}} give the kiss on {{oppositePerson}}\'s Neck",   
    "{{choosedPerson}}, Give a massage to {{oppositePerson}}",
    "Write a love letter to {{oppositePerson}} and read it out loud.",
    "Sing a love song to {{oppositePerson}}.",
    "Take a dance together.",
    "{{choosedPerson}}, Have you ever cheated {{oppositePerson}}?",
    "{{choosedPerson}}, Have you ever lied {{oppositePerson}}?",
    "{{choosedPerson}}, Remove three items of clothing",
    "{{choosedPerson}}, Remove your inner and ask {{oppositePerson}} to kiss on it",
    "Keep your eyes closed until it's your turn again",
    "Seductively eat a banana",
    "Do your best sexy crawl",
    "Try to lick your elbow",
    "bark like a dog for 30 seconds.",
    "Lick {{oppositePerson}}'s ear.",
    "Kiss {{oppositePerson}}'s forehead.",
    "{{choosedPerson}}, Do a liplock each other",
    "{{choosedPerson}}, Do a lipkiss",
    "{{choosedPerson}} Remove your all items of clothing and be naked",
    "{{choosedPerson}} give a massage on {{oppositePerson}} shoulders",
    "{{choosedPerson}} give a kiss to all part of the body of {{oppositePerson}} from leg to bottom. atleast 10 kisses should be given",
    "{{oppositePerson}} remove {{choosedPerson}}'s any one items of clothing",
    "{{choosedPerson}}, Draw the alphabet on {{oppositePerson}} back with your lips and let {{choosedPerson}} find it. if {{oppositePerson}} finds it correctly you have to give a kiss on {{oppositePerson}}'s underwear",
    "Perform a seductive dance on a nursery rhyme.",
    "{{choosedPerson}}, Lick the nose of {{oppositePerson}}",
    "{{choosedPerson}}, Lick upper part of {{oppositePerson}}'s stomach ",
    "Exchange an item of clothing",
    "{{choosedPerson}}, kiss your faviourite body part of {{oppositePerson}}",
    "{{choosedPerson}}, kiss on {{oppositePerson}}'s feet",
    "{{choosedPerson}}, give {{oppositePerson}} a sexy massage",
    "{{oppositePerson}}, give me your most passionate kiss",
    "{{choosedPerson}}, let {{oppositePerson}} handcuff you and tickle you for one minute",
    "{{choosedPerson}}, play the rest of the game in your underwear if you have not naked",
    "{{choosedPerson}}, send {{oppositePerson}} a dirty text of how you want the night to end",
    "Put your mouth to my mouth and do anything BUT kiss. ",
    "Let’s get in the shower, and slowly, sensually wash my hair for me. ",
    "Lick a non-obvious body part, and maybe even suck ",
    "{{oppositePerson}} Sit right beside me and lean in like we will kiss and do a kiss for a minute",
    "Lick a non-obvious body part, and maybe even suck",
    "{{choosedPerson}} Give me a long, slow passionate kiss",
    "{{oppositePerson}}, Help {{choosedPerson}} undress without using your hands",
    "{{oppositePerson}}, Seductively whisper {{choosedPerson}}'s ear the cheesiest, most awful pick up line you can think of.",
    "{{oppositePerson}}, I’ll put 5 small hearts somewhere on my body (using stickers or a skin-safe pen). Find them all and give them each a kiss.",
    "{{oppositePerson}}, Let {{choosedPerson}} wax, shave, or trim some of your body hair. ",
    "{{oppositePerson}}, Count my teeth with your tongue. ",
    "{{oppositePerson}}, Close your eyes and open your mouth. ",
    "Pick me up and throw me over your shoulder!",
    "Tickle my back with a feather, personal massager, or even your tongue.",
    "Undress of all items of clothing if you have not naked and look into my eyes without touching me at all for 1 minute",

];

console.log("Truth Count: " + truths.length,  "Dare Count: " + dares.length)